// <auto-generated />
using Labb2_CodeFirst_LINQ.ContextDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2_CodeFirst_LINQ.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20230421144004_Test Subject")]
    partial class TestSubject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Connect", b =>
                {
                    b.Property<int>("ConnectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("ConnectID");

                    b.HasIndex("SubjectID")
                        .IsUnique();

                    b.ToTable("connects");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudconnectConnectID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("StudconnectConnectID");

                    b.ToTable("student");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"), 1L, 1);

                    b.Property<int>("ConnID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"), 1L, 1);

                    b.Property<int>("ConnectID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.HasIndex("ConnectID");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Connect", b =>
                {
                    b.HasOne("Labb2_CodeFirst_LINQ.Models.Subject", null)
                        .WithOne("Sconnect")
                        .HasForeignKey("Labb2_CodeFirst_LINQ.Models.Connect", "SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Student", b =>
                {
                    b.HasOne("Labb2_CodeFirst_LINQ.Models.Connect", "Studconnect")
                        .WithMany("StudentList")
                        .HasForeignKey("StudconnectConnectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studconnect");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Teacher", b =>
                {
                    b.HasOne("Labb2_CodeFirst_LINQ.Models.Connect", "Tconnect")
                        .WithMany("TeacherList")
                        .HasForeignKey("ConnectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tconnect");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Connect", b =>
                {
                    b.Navigation("StudentList");

                    b.Navigation("TeacherList");
                });

            modelBuilder.Entity("Labb2_CodeFirst_LINQ.Models.Subject", b =>
                {
                    b.Navigation("Sconnect")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
